import { TranslationSchema } from './types';

export const en: TranslationSchema = {
  common: {
    appName: "Workoutron",
    appVersion: "3000",
    fullVersion: "3.1.0-PREVIEW",
    back: "Back",
    cancel: "Cancel",
    confirm: "Confirm",
    done: "Done",
    save: "Save",
    loading: "Loading...",
    errorTitle: "Error",
    storageLimitMsg: "Storage Limit Reached: Please delete some old workouts in your Library to save new ones.",
    storageFullMsg: "Storage Full: Cannot save new workout. Please delete some routines from your Library first.",
    unexpectedError: "An unexpected error occurred while saving."
  },
  header: {
    settings: "Settings"
  },
  nav: {
    library: "Library",
    add: "Add",
    history: "History"
  },
  uploader: {
    analyzingTitle: "Analyzing Gear",
    analyzingDesc: "Identifying equipment and crafting your specialized routine...",
    cameraDenied: "Camera access denied. Try uploading a photo instead.",
    snapTitle: "Snap to Begin",
    snapDesc: "Take a photo of any training gear to generate a custom routine.",
    uploadBtn: "Upload from Library",
    legalInfo: "AI Generation Disclaimer"
  },
  workout: {
    identified: "Identified",
    exitBtn: "Exit Training",
    intensityTitle: "Intensity Mode",
    exerciseLabel: "EXERCISE",
    sets: "SETS",
    reps: "REPS",
    time: "TIME",
    dist: "DIST",
    rest: "REST",
    bodyweight: "Body",
    safetyTitle: "Safety & Context Summary",
    legalDisclaimerBtn: "Legal Disclaimer & Terms",
    legalModalTitle: "Legal Disclaimer",
    legalBody: [
      "The workout routines and exercises generated by Workoutron 3000 are provided by artificial intelligence for informational and motivational purposes only.",
      "Warning: Always consult with a qualified fitness professional or licensed physician before beginning any new exercise program."
    ],
    legalUnderstand: "I Understand",
    startTraining: "Start Training",
    skip: "Skip",
    recovery: "Recovery",
    complete: "Complete",
    doneWithSet: "Done with Set",
    langMismatch: "Generated in different language",
    shareBtn: "Share Routine"
  },
  share: {
    title: "Share Your Routine",
    preview: "Share Preview",
    downloadBtn: "Download Image",
    nativeBtn: "Choose your app",
    twitter: "X (Twitter)",
    facebook: "Facebook",
    whatsapp: "WhatsApp",
    telegram: "Telegram",
    instagram: "Instagram",
    snapchat: "Snapchat",
    copyLink: "Copy Link",
    linkCopied: "Link Copied!",
    generatedBy: "Download Workoutron from Google Play or the Apple App Store"
  },
  library: {
    title: "Your Library",
    searchPlaceholder: "Search your gear...",
    noRoutinesTitle: "No Saved Routines",
    noRoutinesDesc: "Scan some equipment using the camera to build your personal training library.",
    removeTitle: "Remove Routine",
    favAdd: "Add to Favorites",
    favRemove: "Remove from Favorites"
  },
  activity: {
    title: "Activity Hub",
    descPrefix: "Dynamic training history for",
    totalEffort: "Total Effort",
    currentStreak: "Current Streak",
    days: "days",
    consistency: "Consistency",
    intensityKey: "Intensity Key",
    recentProgress: "Recent Progress",
    lastSessions: "Last 10 sessions",
    noActivity: "No activity recorded yet. Start your journey by scanning equipment!",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    scores: {
      none: "None",
      elite: "Elite",
      pro: "Pro",
      good: "Good",
      active: "Active"
    }
  },
  settings: {
    title: "Options",
    subtitle: "Personalize your training experience",
    prefTitle: "Preferences",
    prefDesc: "Choose your measurement standards.",
    unitSystem: "Unit System",
    metric: "Metric",
    imperial: "Imperial",
    audioTitle: "Audio & Feedback",
    audioDesc: "Manage sounds and interface alerts.",
    interfaceSounds: "Interface Sounds",
    muted: "Muted",
    enabled: "Enabled",
    aboutTitle: "About",
    version: "Version",
    aiModel: "AI Model",
    footer: "Built with precision for athletes",
    returnBtn: "Return to Training",
    language: "Language"
  },
  modals: {
    completeTitle: "Workout Complete!",
    completeDesc: "Great job! You've successfully finished all exercises for this session.",
    saveBtn: "Save to Library",
    savedBtn: "Saved in Library",
    viewBtn: "View Routine",
    duplicateTitle: "Duplicate Found",
    duplicateDesc: "You already have \"{name}\" in your library.",
    saveNew: "Save as New Copy",
    updateExisting: "Update Existing Entry"
  }
};